name: build

on: [push]

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --ansi --no-interaction --no-progress
      - name: Run ecs check
        run: vendor/bin/ecs check
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --ansi --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit --colors=always
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: pcov
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --ansi --no-interaction --no-progress
      - name: Run tests with coverage
        run: vendor/bin/phpunit --colors=always --coverage-clover=clover.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
